### ISSUE TITLE
Just two questions

### ISSUE THREAD

**Issue by Eldiablozzz** [umutsevdi/wear-pico#1]
First of all, excellent project!! I wanted to make my own smart watch as well so i will give this one a try. Now the questions:
1) Where can we get 3d print files?
2) Is it ok to charge Lipo Battery with TP4056?? I tried searching Lipo charging module for TP4056 but could only find Li-ion ones.

**Comment by umutsevdi** [comment]
Hi, thanks for your interest and enthusiasm.

The 3D-printed model was built by my friend [@KozhaAkhmet](https://github.com/KozhaAkhmet) who will upload the model in a couple of days.

There have been minor changes in the circuit since the publishment of the paper. I suggest you wait a couple of days before starting to build the circuit. I will let you know about both when they are resolved.

Since the repository is new I'm still updating the documentation. Sorry for the inconvenience.

As for the battery module, I'm afraid I don't have detailed information about the battery circuits in general. However, I don't see an issue with building the circuit using Li-ion batteries.

**Comment by umutsevdi** [comment]
I created two new issues about the topics.
#2 #3

**Comment by Eldiablozzz** [comment]
Thank you for quick reply, I will be waiting for the updates 👍

**Comment by KozhaAkhmet** [comment]
> I created two new issues about the topics. #2 #3

Update: Resolved #2 and #3
